### ISSUE TITLE
八字的月干支和日干支还是和网上的万年历不一样

### ISSUE THREAD

**Issue by collinswang** [6tail/lunar-php#1]
八字的月干支还是和网上的万年历不一样
例子:

1986年 | 4月 | 5日  得出来的是:        丙寅     辛卯    己卯
                             网上的万年历是:  丙寅年 壬辰月 己卯日

**Comment by 6tail** [comment]
@collinswang 1986年4月5日那天，清明交接时刻为：10:06:07，如果按万年历，当天为壬辰月，如果按八字，10:06:07以前是辛卯，以后才是壬辰。我刚刚测试过你说这个按万年历是壬辰，并不是辛卯，请仔细看API文档说明，万年历月干支使用getMonthInGanZhi，八字月干支使用getMonthInGanZhiExact。为便于理解，你可以看示例：八字排盘中，输入1986、4、5、10、6可看到八字是辛卯，如果把分改为7，八字变为壬辰。

**Comment by 6tail** [comment]
万年历和八字的参考依据都不同，差之毫厘谬以千里。万年历正月初一就跨年了，八字立春交接时刻才跨年，怎么可能用万年历来参考呢？

**Comment by collinswang** [comment]
好的.我还一直以为是错的呢.谢谢,我再试下
