### ISSUE TITLE
获取宜和忌方法和其他编程语言判断存在差别，导致无法获取到宜忌事项

### ISSUE THREAD

**Issue by simplephp** [6tail/lunar-php#3]
`/**
   * 获取日忌
   * @param string $monthGanZhi 月干支
   * @param string $dayGanZhi 日干支
   * @return array 忌
   */
  public static function getDayJi($monthGanZhi, $dayGanZhi)
  {
    $l = array();
    $day = LunarUtil::hex(LunarUtil::getJiaZiIndex($dayGanZhi));
    $month = LunarUtil::hex(LunarUtil::getJiaZiIndex($monthGanZhi));
    $right = LunarUtil::$DAY_YI_JI;
    $index = strpos($right, $day . '=');
    // while ($index) { ## 原始的判断
    while ($index > -1) {
      $right = substr($right, $index + 3);
      $left = $right;
      if (strpos($left, '=')) {
        $left = substr($left, 0, strpos($left, '=') - 2);
      }
      $matched = false;
      $months = substr($left, 0, strpos($left, ':'));
      for ($i = 0, $j = strlen($months); $i < $j; $i += 2) {
        $m = substr($months, $i, 2);
        if ($m == $month) {
          $matched = true;
          break;
        }
      }
      if ($matched) {
        $ys = substr($left, strpos($left, ',') + 1, strlen($left));
        for ($i = 0, $j = strlen($ys); $i < $j; $i += 2) {
          $m = substr($ys, $i, 2);
          $l[] = LunarUtil::$YI_JI[hexdec($m)];
        }
        break;
      }
      $index = strpos($right, $day . '=');
    }
    if (count($l) < 1) {
      $l[] = '无';
    }
    return $l;
  }`

宜和忌方法都存在 while($index) 判断问题

**Comment by 6tail** [comment]
感谢，已修改。

**Comment by 6tail** [comment]
v1.1.9 修复日宜忌获取问题。
