### ISSUE TITLE
公历1727年03月23日的农历与寿星不一致

### ISSUE THREAD

**Issue by ghost** [6tail/lunar-php#6]
公历1727年03月23日,寿星显示是三月初一,本项目显示是闰二月初一,农历置闰算法跟寿星不一致么?
当然应该没人需要这么早的农历,我是在做校正的时候发现这个问题的

**Comment by 6tail** [comment]
厉害，这都能发现。确实只是利用寿星算法计算节气时间，置闰算法是我自己写的，可能有特殊情况计算错误，我检查下。

**Comment by 6tail** [comment]
寿星上查到谷雨是1727-04-21 00:40:08，为何节气是4月20日，我很懵。。。

**Comment by ghost** [comment]
朋友你好,方便加上QQ交流一下么,我申请加群了

**Comment by ghost** [comment]
没有问题了
